###
POST http://localhost:8080/users
Content-Type: application/json

{
    "username": "admin",
    "password": "123456",
    "passwordConfirmation": "123456"
}


###
GET http://localhost:8080/api/users
